# CMake generated Testfile for 
# Source directory: C:/blender-git/blender/source/blender
# Build directory: C:/blender-git/build_windows_x64_vc17_Release/source/blender
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
subdirs("datatoc")
subdirs("editors")
subdirs("windowmanager")
subdirs("animrig")
subdirs("asset_system")
subdirs("blenkernel")
subdirs("blenlib")
subdirs("bmesh")
subdirs("draw")
subdirs("render")
subdirs("blenfont")
subdirs("blentranslation")
subdirs("blenloader")
subdirs("depsgraph")
subdirs("ikplugin")
subdirs("simulation")
subdirs("geometry")
subdirs("gpu")
subdirs("imbuf")
subdirs("imbuf/intern/oiio")
subdirs("nodes")
subdirs("modifiers")
subdirs("gpencil_modifiers_legacy")
subdirs("sequencer")
subdirs("shader_fx")
subdirs("io")
subdirs("functions")
subdirs("makesdna")
subdirs("makesrna")
subdirs("compositor")
subdirs("blendthumb")
subdirs("imbuf/intern/openexr")
subdirs("imbuf/intern/cineon")
subdirs("python")
subdirs("freestyle")
